on:
  workflow_dispatch:
  push:
    tags:
      - "v**"

name: Rust release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: login
        run: cargo login ${{ secrets.CRATES_TOKEN }}

      - name: publish
        run: cargo publish
